### ISSUE TITLE
Custom icons

### ISSUE THREAD

**Issue by KaKi87** [Rarcoon/Discord-Rich-Presence-Tool#4]
Hello,

Is there a way to put custom game icons ?

Thanks.

**Comment by viggou** [comment]
Only if you download the source and recompile it.

**Comment by KaKi87** [comment]
Oh. Would it be possible to add this feature ?

**Comment by Rarcoon** [comment]
Hi, sorry for the super late reply!

Unfortunately, it's not possible to add additional images at runtime due to a limitation of the Discord Rich Presence API. However, you can recompile DRPT using your own [Discord Rich Presence application](https://discordapp.com/developers/applications/) to add your own images.
